// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace VKS.Measures.RC {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VKS.Measures.RC.Exceptions", typeof(Exceptions).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NotSupported_MeasurementSystem {
            get {
                return ResourceManager.GetString("NotSupported_MeasurementSystem", resourceCulture);
            }
        }
        
        public static string NotSupported_FormatSequence {
            get {
                return ResourceManager.GetString("NotSupported_FormatSequence", resourceCulture);
            }
        }
        
        public static string NotSupported_NANAsScale {
            get {
                return ResourceManager.GetString("NotSupported_NANAsScale", resourceCulture);
            }
        }
        
        public static string PositiveValuesNotAllowed {
            get {
                return ResourceManager.GetString("PositiveValuesNotAllowed", resourceCulture);
            }
        }
        
        public static string NotSupported_InfiniteScales {
            get {
                return ResourceManager.GetString("NotSupported_InfiniteScales", resourceCulture);
            }
        }
        
        public static string NonPositiveValuesNotAllowed {
            get {
                return ResourceManager.GetString("NonPositiveValuesNotAllowed", resourceCulture);
            }
        }
        
        public static string NotSupported_NANAsValue {
            get {
                return ResourceManager.GetString("NotSupported_NANAsValue", resourceCulture);
            }
        }
        
        public static string NegativeValuesNotAllowed {
            get {
                return ResourceManager.GetString("NegativeValuesNotAllowed", resourceCulture);
            }
        }
        
        public static string NonNegativeValuesNotAllowed {
            get {
                return ResourceManager.GetString("NonNegativeValuesNotAllowed", resourceCulture);
            }
        }
    }
}
