// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace VKS.Measures.RC {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ISOUQuantifiers {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ISOUQuantifiers() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VKS.Measures.RC.ISOUQuantifiers", typeof(ISOUQuantifiers).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string A_Volume {
            get {
                return ResourceManager.GetString("A_Volume", resourceCulture);
            }
        }
        
        public static string A_Time {
            get {
                return ResourceManager.GetString("A_Time", resourceCulture);
            }
        }
        
        public static string A_Area {
            get {
                return ResourceManager.GetString("A_Area", resourceCulture);
            }
        }
        
        public static string A_Force {
            get {
                return ResourceManager.GetString("A_Force", resourceCulture);
            }
        }
        
        public static string F_Length {
            get {
                return ResourceManager.GetString("F_Length", resourceCulture);
            }
        }
        
        public static string F_Mass {
            get {
                return ResourceManager.GetString("F_Mass", resourceCulture);
            }
        }
        
        public static string A_Length {
            get {
                return ResourceManager.GetString("A_Length", resourceCulture);
            }
        }
        
        public static string F_Temperature {
            get {
                return ResourceManager.GetString("F_Temperature", resourceCulture);
            }
        }
        
        public static string F_Force {
            get {
                return ResourceManager.GetString("F_Force", resourceCulture);
            }
        }
        
        public static string F_Area {
            get {
                return ResourceManager.GetString("F_Area", resourceCulture);
            }
        }
        
        public static string A_Mass {
            get {
                return ResourceManager.GetString("A_Mass", resourceCulture);
            }
        }
        
        public static string A_Temperature {
            get {
                return ResourceManager.GetString("A_Temperature", resourceCulture);
            }
        }
        
        public static string F_Volume {
            get {
                return ResourceManager.GetString("F_Volume", resourceCulture);
            }
        }
        
        public static string F_Time {
            get {
                return ResourceManager.GetString("F_Time", resourceCulture);
            }
        }
    }
}
