// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace VKS.Measures.RC {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ISOUScales {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ISOUScales() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VKS.Measures.RC.ISOUScales", typeof(ISOUScales).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Abbr_M03 {
            get {
                return ResourceManager.GetString("Abbr_M03", resourceCulture);
            }
        }
        
        public static string Abbr_M02 {
            get {
                return ResourceManager.GetString("Abbr_M02", resourceCulture);
            }
        }
        
        public static string Abbr_M01 {
            get {
                return ResourceManager.GetString("Abbr_M01", resourceCulture);
            }
        }
        
        public static string Prefix_F12 {
            get {
                return ResourceManager.GetString("Prefix_F12", resourceCulture);
            }
        }
        
        public static string Prefix_F24 {
            get {
                return ResourceManager.GetString("Prefix_F24", resourceCulture);
            }
        }
        
        public static string Abbr_F18 {
            get {
                return ResourceManager.GetString("Abbr_F18", resourceCulture);
            }
        }
        
        public static string Prefix_M09 {
            get {
                return ResourceManager.GetString("Prefix_M09", resourceCulture);
            }
        }
        
        public static string Abbr_F15 {
            get {
                return ResourceManager.GetString("Abbr_F15", resourceCulture);
            }
        }
        
        public static string Prefix_M06 {
            get {
                return ResourceManager.GetString("Prefix_M06", resourceCulture);
            }
        }
        
        public static string Abbr_F12 {
            get {
                return ResourceManager.GetString("Abbr_F12", resourceCulture);
            }
        }
        
        public static string Prefix_M03 {
            get {
                return ResourceManager.GetString("Prefix_M03", resourceCulture);
            }
        }
        
        public static string Prefix_M02 {
            get {
                return ResourceManager.GetString("Prefix_M02", resourceCulture);
            }
        }
        
        public static string Abbr_M24 {
            get {
                return ResourceManager.GetString("Abbr_M24", resourceCulture);
            }
        }
        
        public static string Abbr_M21 {
            get {
                return ResourceManager.GetString("Abbr_M21", resourceCulture);
            }
        }
        
        public static string Prefix_F21 {
            get {
                return ResourceManager.GetString("Prefix_F21", resourceCulture);
            }
        }
        
        public static string Prefix_F06 {
            get {
                return ResourceManager.GetString("Prefix_F06", resourceCulture);
            }
        }
        
        public static string Prefix_M21 {
            get {
                return ResourceManager.GetString("Prefix_M21", resourceCulture);
            }
        }
        
        public static string Prefix_M01 {
            get {
                return ResourceManager.GetString("Prefix_M01", resourceCulture);
            }
        }
        
        public static string Prefix_F18 {
            get {
                return ResourceManager.GetString("Prefix_F18", resourceCulture);
            }
        }
        
        public static string Prefix_F15 {
            get {
                return ResourceManager.GetString("Prefix_F15", resourceCulture);
            }
        }
        
        public static string Abbr_F09 {
            get {
                return ResourceManager.GetString("Abbr_F09", resourceCulture);
            }
        }
        
        public static string Abbr_F06 {
            get {
                return ResourceManager.GetString("Abbr_F06", resourceCulture);
            }
        }
        
        public static string Prefix_M24 {
            get {
                return ResourceManager.GetString("Prefix_M24", resourceCulture);
            }
        }
        
        public static string Abbr_F24 {
            get {
                return ResourceManager.GetString("Abbr_F24", resourceCulture);
            }
        }
        
        public static string Abbr_F03 {
            get {
                return ResourceManager.GetString("Abbr_F03", resourceCulture);
            }
        }
        
        public static string Abbr_M18 {
            get {
                return ResourceManager.GetString("Abbr_M18", resourceCulture);
            }
        }
        
        public static string Abbr_F01 {
            get {
                return ResourceManager.GetString("Abbr_F01", resourceCulture);
            }
        }
        
        public static string Abbr_M15 {
            get {
                return ResourceManager.GetString("Abbr_M15", resourceCulture);
            }
        }
        
        public static string Abbr_M09 {
            get {
                return ResourceManager.GetString("Abbr_M09", resourceCulture);
            }
        }
        
        public static string Abbr_M12 {
            get {
                return ResourceManager.GetString("Abbr_M12", resourceCulture);
            }
        }
        
        public static string Abbr_F02 {
            get {
                return ResourceManager.GetString("Abbr_F02", resourceCulture);
            }
        }
        
        public static string Prefix_F09 {
            get {
                return ResourceManager.GetString("Prefix_F09", resourceCulture);
            }
        }
        
        public static string Prefix_M18 {
            get {
                return ResourceManager.GetString("Prefix_M18", resourceCulture);
            }
        }
        
        public static string Prefix_F03 {
            get {
                return ResourceManager.GetString("Prefix_F03", resourceCulture);
            }
        }
        
        public static string Prefix_F02 {
            get {
                return ResourceManager.GetString("Prefix_F02", resourceCulture);
            }
        }
        
        public static string Prefix_F01 {
            get {
                return ResourceManager.GetString("Prefix_F01", resourceCulture);
            }
        }
        
        public static string Prefix_M15 {
            get {
                return ResourceManager.GetString("Prefix_M15", resourceCulture);
            }
        }
        
        public static string Abbr_F21 {
            get {
                return ResourceManager.GetString("Abbr_F21", resourceCulture);
            }
        }
        
        public static string Prefix_M12 {
            get {
                return ResourceManager.GetString("Prefix_M12", resourceCulture);
            }
        }
        
        public static string Abbr_M06 {
            get {
                return ResourceManager.GetString("Abbr_M06", resourceCulture);
            }
        }
    }
}
